version: "3.8"

services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app

  db:
    image: postgres:11
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

# declare volumes here =>
volumes:
  postgres-data:
